var namespaceasiopal =
[
    [ "ChannelRetry", "classasiopal_1_1ChannelRetry.html", "classasiopal_1_1ChannelRetry" ],
    [ "Executor", "classasiopal_1_1Executor.html", "classasiopal_1_1Executor" ],
    [ "IAsyncChannel", "classasiopal_1_1IAsyncChannel.html", "classasiopal_1_1IAsyncChannel" ],
    [ "IChannelCallbacks", "structasiopal_1_1IChannelCallbacks.html", "structasiopal_1_1IChannelCallbacks" ],
    [ "IListener", "classasiopal_1_1IListener.html", "classasiopal_1_1IListener" ],
    [ "IO", "classasiopal_1_1IO.html", "classasiopal_1_1IO" ],
    [ "IOpenDelayStrategy", "classasiopal_1_1IOpenDelayStrategy.html", "classasiopal_1_1IOpenDelayStrategy" ],
    [ "ExponentialBackoffStrategy", "classasiopal_1_1ExponentialBackoffStrategy.html", "classasiopal_1_1ExponentialBackoffStrategy" ],
    [ "IPEndpoint", "classasiopal_1_1IPEndpoint.html", "classasiopal_1_1IPEndpoint" ],
    [ "IResource", "structasiopal_1_1IResource.html", "structasiopal_1_1IResource" ],
    [ "IResourceManager", "structasiopal_1_1IResourceManager.html", "structasiopal_1_1IResourceManager" ],
    [ "LoggingConnectionCondition", "classasiopal_1_1LoggingConnectionCondition.html", "classasiopal_1_1LoggingConnectionCondition" ],
    [ "ResourceManager", "classasiopal_1_1ResourceManager.html", "classasiopal_1_1ResourceManager" ],
    [ "SerialChannel", "classasiopal_1_1SerialChannel.html", "classasiopal_1_1SerialChannel" ],
    [ "SerialSettings", "structasiopal_1_1SerialSettings.html", "structasiopal_1_1SerialSettings" ],
    [ "SocketChannel", "classasiopal_1_1SocketChannel.html", "classasiopal_1_1SocketChannel" ],
    [ "SocketHelpers", "classasiopal_1_1SocketHelpers.html", null ],
    [ "Synchronized", "classasiopal_1_1Synchronized.html", "classasiopal_1_1Synchronized" ],
    [ "TCPClient", "classasiopal_1_1TCPClient.html", "classasiopal_1_1TCPClient" ],
    [ "TCPServer", "classasiopal_1_1TCPServer.html", "classasiopal_1_1TCPServer" ],
    [ "ThreadPool", "classasiopal_1_1ThreadPool.html", "classasiopal_1_1ThreadPool" ],
    [ "TimeConversions", "classasiopal_1_1TimeConversions.html", null ],
    [ "Timer", "classasiopal_1_1Timer.html", "classasiopal_1_1Timer" ],
    [ "TLSConfig", "structasiopal_1_1TLSConfig.html", "structasiopal_1_1TLSConfig" ],
    [ "UTCTimeSource", "classasiopal_1_1UTCTimeSource.html", "classasiopal_1_1UTCTimeSource" ],
    [ "SSLContext", "classasiopal_1_1SSLContext.html", "classasiopal_1_1SSLContext" ],
    [ "TLSClient", "classasiopal_1_1TLSClient.html", "classasiopal_1_1TLSClient" ],
    [ "TLSContext", "classasiopal_1_1TLSContext.html", "classasiopal_1_1TLSContext" ],
    [ "TLSServer", "classasiopal_1_1TLSServer.html", "classasiopal_1_1TLSServer" ],
    [ "TLSStreamChannel", "classasiopal_1_1TLSStreamChannel.html", "classasiopal_1_1TLSStreamChannel" ]
];